### ISSUE TITLE
Add google analytics/etc to the blog/website

### ISSUE THREAD

**Issue by ctron** [drogue-iot/blog.drogue.io#6]

**Comment by roshanthankar** [comment]
Hello, I have knowledge of HTML but I haven't contributed to any open-source project earlier, I'm a beginner. I would like to contribute to this project.
So, How should I start can anyone suggest to me the way to start contributing.

**Comment by ctron** [comment]
I am sorry. Actually this issued is already solved, I forgot to close it.
